# Generated by Django 5.0.6 on 2024-05-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_studymaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="materials/"),
        ),
    ]
